# fly.toml file generated for muddy-flower-2237 on 2022-02-11T01:20:52-05:00

app = "muddy-flower-2237"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 50051

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
